### ISSUE TITLE
Update PhoneNumberMetadata

### ISSUE THREAD

**Issue by szymon-jez** [socialpaymentsbv/ex_phone_number#43]
Refs #42, #39, #33

# Problem

The library uses outdated metadata. Therefore it is not validating/formatting some numbers right.

# Solution

To upgrade the metadata it is also necessary to upgrade the code.

**Comment by josemrb** [comment]
## Tasks

### Add method `getLengthOfGeographicalAreaCode`

Implement function

- [ ] [getLengthOfGeographicalAreaCode](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L1269)

and corresponding test

- [ ] [testGetLengthOfGeographicalAreaCode](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L358)

### Add method `getLengthOfNationalDestinationCode`

Implement function

- [ ] [getLengthOfNationalDestinationCode](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L1332)

and corresponding test

- [ ] [testGetLengthOfNationalDestinationCode](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L393)

### Add method `getCountryMobileToken`

Implement function

- [ ] [getCountryMobileToken](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L1395)

and corresponding test

- [ ] [testGetCountryMobileToken](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L435)

### Add method `isPossibleNumberForType`

Implement function

- [ ] [isPossibleNumberForType](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L3382)

and corresponding tests

- [ ] [testIsPossibleNumberForType_DifferentTypeLengths](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L1900)
- [ ] [testIsPossibleNumberForType_LocalOnly](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L1945)
- [ ] [testIsPossibleNumberForType_DataMissingForSizeReasons](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L1959)
- [ ] [testIsPossibleNumberForType_NumberTypeNotSupportedForRegion](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L1976)

### Add method `isPossibleNumberForTypeWithReason`

Implement function

- [ ] [isPossibleNumberForTypeWithReason](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L3560)

and corresponding tests

- [ ] [testIsPossibleNumberForTypeWithReason_DifferentTypeLengths](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2035)
- [ ] [testIsPossibleNumberForTypeWithReason_LocalOnly](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2117)
- [ ] [testIsPossibleNumberForTypeWithReason_DataMissingForSizeReasons](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2138)
- [ ] [testIsPossibleNumberForTypeWithReason_NumberTypeNotSupportedForRegion](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2167)
- [ ] [testIsPossibleNumberForTypeWithReason_FixedLineOrMobile](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2231)

### Add method `truncateTooLongNumber`

Implement function

- [ ] [truncateTooLongNumber](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L3632)

and corresponding test

- [ ] [testTruncateTooLongNumber](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L2325)

### Add method `canBeInternationallyDialled`

Implement function

- [ ] [canBeInternationallyDialled](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L4610)

and corresponding test

- [ ] [testCanBeInternationallyDialled](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L4157)

### Add method `isAlphaNumber`

Implement function

- [ ] [isAlphaNumber](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L3328)

and corresponding test

- [ ] [testIsAlphaNumber](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L4173)

### Review method `parse`

Review function

- [ ] [parse](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil.js#L4099)

and add new tests

- [ ] [testParseNumbersWithPlusWithNoRegion](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3349)
- [ ] [testParseExtensions](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3409)
- [ ] [testParseHandlesLongExtensionsWithExplicitLabels](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3555)
- [ ] [testParseHandlesLongExtensionsWithAutoDiallingLabels](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3613)
- [ ] [testParseHandlesShortExtensionsWithAmbiguousChar](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3644)
- [ ] [testParseHandlesShortExtensionsWhenNotSureOfLabel](https://github.com/google/libphonenumber/blob/v8.12.20/javascript/i18n/phonenumbers/phonenumberutil_test.js#L3674)

### Current Test Suite

- [ ] Fix currently failing tests (236 tests, 8 failures)

**Comment by icecapp** [comment]
I've been running some tests and noticed an area code that was [recently introduced in Alberta, Canada](https://crtc.gc.ca/eng/archive/2019/2019-130.htm), that would fail the `is_valid_number?/1` test.

```elixir
iex(33)> {:ok, parsed} = ExPhoneNumber.parse("368.551.0368", "CA") 
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 1,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 3685510368,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
 ```
(fails with `"US"` as well)

[This js port](https://github.com/ruimarinho/google-libphonenumber) validates the previous number properly ([see sandbox](https://codesandbox.io/s/wild-platform-mdoj2?file=/src/index.js)) 

OP stated:
> To upgrade the metadata it is also necessary to upgrade the code.

My question: why are all methods listed above needed in order to get the metadata up-to-date? And wouldn't that mean, to a large extent, that `is_valid_number?/1` would be broken until all this is implemented?

**Comment by josemrb** [comment]
> My question: why are all methods listed above needed in order to get the metadata up-to-date?

Because they are needed to handle the newer metadata.

> And would that mean that is_valid_number?/1 is broken until all this is implemented?

Yes, although it isn't broken, just outdated.

You could build the current `develop` branch as it contains the latest metadata (8.12.27) but it will fail if it comes across a new case that has not been implemented (239 tests, 8 failures)

```ex
iex(1)> {:ok, parsed} = ExPhoneNumber.parse("368.551.0368", "CA")
{:ok,
  %ExPhoneNumber.Model.PhoneNumber{
              country_code: 1,
              country_code_source: nil,
              extension: nil,
              italian_leading_zero: nil,
              national_number: 3685510368,
              number_of_leading_zeros: nil,
              preferred_domestic_carrier_code: nil,
              raw_input: nil
  }}
iex(2)> ExPhoneNumber.is_valid_number?(parsed)
true
```

As the metadata changes every 2-3 weeks, it is very likely that you will find a phone number that does not pass the validation even if it is "real". See [Falsehoods About Phone Numbers](https://github.com/google/libphonenumber/blob/master/FALSEHOODS.md).

**Comment by icecapp** [comment]
Thanks for the quick reply.

Just wondering, in general, what is the delay for mirroring official libphonenumber, as my client implementation of libphonenumber validates certain numbers that ex_phone_number doesn't.

Nevertheless respect, kudos and many thanks for developing, open-sourcing and maintaining this library. 🤜

**Comment by szymon-jez** [comment]
> Just wondering, in general, what is the delay for mirroring official libphonenumber

https://github.com/socialpaymentsbv/ex_phone_number/blob/develop/README.md states the currently used metadata version. This should give you enough information to see the delay.

**Comment by josemrb** [comment]
Nothing in particular, I haven't had enough time, pending changes have accumulated and the code is complex in some parts, although the latter is the result of following the upstream project since this is almost a function by function port.

**Comment by lohayon** [comment]
I join here the conversation: 
`The library uses outdated metadata. Therefore it is not validating/formatting some numbers right.`
We also encountered this issue. We potentially want to add some prefixes before the official document is released with these prefixes. 
I wonder if it would be possible to make the document path dynamic and configurable.
 
Thanks
